### ISSUE TITLE
Add Grunt-based tasks

### ISSUE THREAD

**Issue by necolas** [flightjs/generator-flight#7]
Provide a way for people to automate the creation of a production-optimized build, and do things like run lint tasks. I have some thoughts:
- Avoid grunt-karma. I haven't had a great experience using it and don't like the duplication it involves when you want to watch files. Prefer to stick to Karma au naturelle.
- Prod build should switch out RequireJS for Almond in the optimized AMD bundle. It's an easy win and simple to configure with the grunt requirejs task.
- We probably want most of the features of grunt-usemin - hashing inline images, etc., (see how it's used in other Yeoman generators), but it's a bit of a monolithic mess at the moment (some of that is partly my fault) and under going an opaque rewrite. Open to suggestions on what to do.

@cameronhunter, are you interested in doing this? I've hardly started on it and what I have is completely disposable. So if you want to start this afresh, that would be awesome.

**Comment by cameronhunter** [comment]
I'll have a look into it over the next few days.

**Comment by passy** [comment]
Would you like to add support for compass or some other CSS preprocessor through grunt?

**Comment by necolas** [comment]
Hey. Probably something like autoprefixer at some point. Nothing else though.

**Comment by passy** [comment]
I played around with a grunt on a newly generated flight project today and came up with this: https://gist.github.com/passy/7e11fbb74b09405bfae5

Before this could be turned into a PR, there are a few points that are worth discussing. Do you want to have any support for Karma within grunt at all or just stick to the `npm test` script? What should happen to `bower_components` during the build step? I tried using uglify as a stepping stone to copy them over to `dist`, but this is not only painfully slow due to all the garbage some authors put in their bower packages, but also loses other assets like css files, that could be in use by the app. I'm also not too familiar with almond. There appears to be an option to replace `require.js` automatically with almond, but I had no luck so far with the options I used.

Other than that, the live server works, including autoprefixing and livereloading; so does pixel/vector graphics compression and HTML minification.

**Comment by necolas** [comment]
Cool, thanks for kicking this off :)
1. I'm not sold on grunt-karma because: to autowatch you have to repeating a list of files to watch that are already listed in the karma config; and it uses the unstable version of Karma. This is why I prefer to just use Karma directly in a separate process.
2. Not sure what the issue with the Bower components is. There are only 3-4 JS files that aren't handled by require.js – jquery, the two es5-shim files…that might be it. They can be explicitly listed. If people add more non-AMD JS libs later, they can update the Grunt config as required.
3. I can help sort out the requirejs/almond switch as I've got the setup on a project I'm doing at work.

Some comments on the gist:
- It's really big and unclear what is going on. Some of this is just a drawback of using Grunt – massive config, no clear pipeline. But hopefully we can find something that is a good balance.
- `yeomanConfig`/`yeoman` should just be named `dir`.
- Why use `regarde` instead of grunt-watch? The regarde repo says it's deprecated.
- What do you need all the connect configuration for? Why for tests and dist?
- What's this line for? `!<%= yeoman.dist %>/.git*`
- This line isn't needed in the jshint config: `!<%= yeoman.app %>/js/vendor/*`
- Why is the autoprefixer destination a temporary directory? And why does the cssmin task combine the the temp directory's CSS with the source?
- Are the image/svg tasks just optimizing them, not doing any hashing of the files?
- What is `replaceRequireScript`? I don't see that option in the requirejs task docs.
- What do the `bower` and `concurrent` tasks do?

**Comment by passy** [comment]
> I'm not sold on grunt-karma because: to autowatch you have to repeating a list of files to watch that are already listed in the karma config; and it uses the unstable version of Karma. This is why I prefer to just use Karma directly in a separate process.

Fair enough. I got burned by their versioning scheme, too. I hope this will stabilize over time.

> Why use regarde instead of grunt-watch? The regarde repo says it's deprecated.

It is, unfortunately its successor `grunt-contrib-watch` has some major issues with livereloading at the moment: https://github.com/yeoman/generator-webapp/issues?labels=livereload&page=1&state=open So `grunt-regarde` is still the best option at the moment until those issues are sorted out.

> What do you need all the connect configuration for? Why for tests and dist?

Right, if you use a stand-alone karma configuration those aren't needed.

> What's this line for? !<%= yeoman.dist %>/.git*

That is in there to allow people to keep a separate git repository in `dist/` just for deployment. I used this before so I could push basically the whole `dist` folder to heroku.

> Why is the autoprefixer destination a temporary directory? And why does the cssmin task combine the the temp directory's CSS with the source?

The second part is indeed a mistake. There shouldn't be any need to combine both. The temporary directory is there to keep the `app` and `dist` directories untouched while the development server is running.

> Are the image/svg tasks just optimizing them, not doing any hashing of the files?

Right, the hashing part would require an additional step either with `grunt-rev` or `grunt-filerev`, but replacing the references would require `usemin`. Since you expressed some concerns about it, I did not include that.

> What is replaceRequireScript? I don't see that option in the requirejs task docs.
> Found it in the [almond docs](https://github.com/asciidisco/grunt-requirejs/blob/master/docs/almondIntegration.md) for the task, but as I said, it doesn't work in this configuration, so we should replace it with what you have.
> 
> What do the bower and concurrent tasks do?

`grunt-bower-requirejs` allows you to install and automatically wire-up bower components with your require.js config. So when you execute `grunt bower`, it updates your `main.js` with all components listed in `bower.json`.

`grunt-concurrent` just parallelizes the execution of tasks, that do not depend on each other for performance benefits. Currently, for `server` and `test`, it should be removed though, because with only one entry it only adds a (minor) overhead.

Do you want me to put this into a pull request with the changes discussed here so we can refine it further?

**Comment by necolas** [comment]
Thanks!

> Do you want me to put this into a pull request with the changes discussed here so we can refine it further?

Yeah, that sounds good. I'll make a branch so we can iterate on it in there and then just squash / cleanup once we're happy with the setup.

**Comment by necolas** [comment]
We're not going to be using Grunt. Really basic Gulp setup will be included next release.
